### ISSUE TITLE
ctx.createProgram is not returning an object

### ISSUE THREAD

**Issue by emctague** [antoineMoPa/cinema#1]
Hi! On my system (Firefox 53.0a1 Nightly on Linux), it seems that `ctx.program` is not being set to an object (likely because `ctx.createProgram()` is failing, or perhaps it is not being called prior to the calling of `draw_ctx`.

```
TypeError: Argument 1 of WebGLRenderingContext.getUniformLocation is not an object. - cinema.js:261:29
	draw_ctx https://antoinemopa.github.io/cinema/js/cinema.js:261:29
	draw https://antoinemopa.github.io/cinema/js/cinema.js:325:9
```

It should be noted that this could possibly be due to an issue with my graphics card - it has issues with OpenGL 3.3 support, despite claiming to support it.

**Comment by emctague** [comment]
Addendum: It works perfectly fine in Chromium on the same system. Definitely a cross-browser support issue, or a WebGL issue in firefox.

**Edit**: WebGL 2 seems to be enabled on Firefox, so there shouldn't be any issue with WebGL support — it's probably some other cross-browser support issue.

**Comment by antoineMoPa** [comment]
Looks like this is a firefox nightly bug 😛

**Comment by emctague** [comment]
Update: Now fixed in latest nightly release.

**Comment by antoineMoPa** [comment]
Thank u and thank firefox nightly
